### ISSUE TITLE
Make ignore file configurable

### ISSUE THREAD

**Issue by thom4parisot** [jonschlinkert/glob-fs-gitignore#1]
Hello,

it would be super handy to be able to configure the dotfile name/location.
This way this middleware could help to collect patterns in `.dockerignore` and many other `.xxignore` files compatible with gitignore patterns.

What do you think?

**Comment by jonschlinkert** [comment]
great idea! I can implement as soon as I have a chance, or would you want to do a pr?

**Comment by thom4parisot** [comment]
I can have a go at it — I wanted to make sure this proposal would be welcomed before spending time on it :-)

**Comment by jonschlinkert** [comment]
great! any feedback or ideas on how to improve glob-fs/plugins are welcome too
