### ISSUE TITLE
Parameter order when calling micromatch any(...)

### ISSUE THREAD

**Issue by arisahl** [jonschlinkert/glob-fs-gitignore#2]
When trying to use glob-fs-gitignore 0.1.5 just right out of the box, through glob-fs 0.1.6 and having gitignore option is set to true, I had to do the following modification in index.js, to get it running:

``` js
  var isMatch = function (fp) {
    //return mm().any(ignorePatterns, fp, opts); //<-- error
    return mm().any(fp, ignorePatterns, opts); //<-- fix
  };
```

**Comment by jonschlinkert** [comment]
should be fixed
